### PR TITLE
Refactor code to improve structure, readability and compatability

### PR DESCRIPTION
**Pull request by antonslyzhko**
Fix request sending if file name is not in English or/and has symbols.
Fix button positioning.
Refactor code structure.
Remove redundant files.

### CODE REVIEW

**Comment by antonslyzhko** [comment]
Hello from 🇺🇦 @Kharg !
I found your extension very helpful, but when I installed it, I had issues with sending requests to back-end. 
So I decided to refactore your code.

**Comment by Kharg** [comment]
Thank you so much for your contribution, I will review and test the code and merge it once I finish.

😃

**Comment by Kharg** [comment]
@AntonSlyzhko almost perfect, would you just mind giving better constant names instead of using only "s" and "g" in the extender?

Your pull request is really appreciated!

**Comment by antonslyzhko** [comment]
Done naming fix!

**Pull request merged**
